# Generated by Django 5.1.3 on 2024-11-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
