# Generated by Django 5.1.3 on 2024-11-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
