# Generated by Django 5.1.3 on 2024-11-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_remove_post_anonymous_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_images/'),
        ),
    ]
