# Generated by Django 5.1.3 on 2024-11-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_rename_author_comment_user_remove_post_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
