# Generated by Django 5.1.3 on 2024-11-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_rename_user_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, help_text='Cismin rengi (örn: kırmızı, mavi)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='material',
            field=models.CharField(blank=True, help_text='Cismin materyali (örn: ahşap, plastik, metal)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='shape',
            field=models.CharField(blank=True, help_text='Cismin şekli (örn: küresel, silindirik)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.FloatField(blank=True, help_text='Cismin boyutu (örneğin: uzunluk, çap)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.FloatField(blank=True, help_text='Cismin ağırlığı (kg cinsinden)', null=True),
        ),
    ]
