# Generated by Django 5.1.3 on 2024-11-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0019_alter_profile_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
