# Generated by Django 5.1.3 on 2024-11-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
