# Generated by Django 5.1.3 on 2024-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0021_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
