# Generated by Django 5.1.3 on 2024-11-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0022_post_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='name',
            field=models.CharField(default='Unnamed Object', max_length=255),
        ),
        migrations.AddField(
            model_name='object',
            name='shape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(blank=True, to='objects.tag'),
        ),
        migrations.AddField(
            model_name='object',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
