# Generated by Django 5.1.3 on 2024-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0023_object_color_object_description_object_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='matched_object',
            field=models.TextField(blank=True, null=True),
        ),
    ]
