# Generated by Django 5.1.3 on 2024-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0024_post_matched_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
