# Generated by Django 5.1.3 on 2024-12-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0025_post_solved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
