# Generated by Django 5.1.3 on 2024-12-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0026_alter_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
