# Generated by Django 5.1.3 on 2024-12-13 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0029_comment_last_edited_by_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.CreateModel(
            name='PostFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='objects.post')),
            ],
            options={
                'unique_together': {('post', 'feature_type', 'value')},
            },
        ),
    ]
