# Generated by Django 5.1.3 on 2024-12-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0030_post_description_postfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, help_text='Colors of the object', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='material',
            field=models.CharField(blank=True, help_text='Materials of the object', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='shape',
            field=models.CharField(blank=True, help_text='Shapes of the object', max_length=500, null=True),
        ),
    ]
