"""
Django settings for swe573_fall_2024 project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from google.oauth2 import service_account
from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Statik dosyaların kaynak klasörü
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # 'collectstatic' çıktıları için hedef klasör

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"  # Yüklenen medya dosyalarının saklanacağı klasör
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# AWS S3 settings
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
# AWS_ACCESS_KEY_ID = os.getenv("AKIAQ4NSBDI73DXYVGVC")
# AWS_SECRET_ACCESS_KEY = os.getenv("ihmw/TbdBw8oWSnGyRzyPLh01Zgfu5u0VT9udGRi")
# AWS_STORAGE_BUCKET_NAME = 'swe573finder-media'  # Replace with your actual bucket name
# AWS_S3_REGION_NAME = 'eu-north-1'  # e.g., 'us-west-1'
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

# # Media files storage settings
# MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

# DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
# GS_BUCKET_NAME = 'swe573-media'  # Bucket adınız
# GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
#     "/Users/yilmazunal/Desktop/SWE573-Software-Development-Practice/swe573_fall_2024/swe-573-fall-2024-6abce562c418.json"
# )
# # Optional but recommended settings
# GS_PROJECT_ID = 'swe-573-fall-2024'
# GS_DEFAULT_ACL = 'publicRead'  # Makes uploaded files publicly readable

# # Media settings
# MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'
# DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
# MEDIA_ROOT = 'media/'  # Local media directory for development

# # Make files publicly readable
# GS_FILE_OVERWRITE = False  # Don't overwrite files with the same name
# GS_QUERYSTRING_AUTH = False  # Don't add authentication tokens to URLs
# # Medya Dosyalarının URL'si
# MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'


 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y%-m80((gm!odadtwj%zycme67&5ai)-%4ell5%36lzb@l1j8p'

# SECURITY WARNING: don't run with debug turned on in production!
CSRF_TRUSTED_ORIGINS = [
    'https://swe573finder-849897479442.us-central1.run.app',
    'https://swe573-software-development-practice.onrender.com', # Cloud Run URL'si
]
ALLOWED_HOSTS = ['*']
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'objects',
]

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'swe573_fall_2024.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [os.path.join(BASE_DIR, 'objects', 'templates')], 
        'DIRS': [os.path.join(BASE_DIR, 'templates', 'partials')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'swe573_fall_2024.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'objectfinderdb',  # AWS RDS Veritabanı Adı
        'USER': 'swe573',          # AWS RDS Kullanıcı Adı
        'PASSWORD': 'swe573user',  # AWS RDS Şifresi
        'HOST': 'objectfinderdb.cjawmsuoif2a.eu-north-1.rds.amazonaws.com',  # AWS RDS Endpoint
        'PORT': '5432',            # PostgreSQL Varsayılan Portu
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Yüklenen medya dosyalarının kaydedileceği yer
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
